### ISSUE TITLE
Delete "deleted page"

### ISSUE THREAD

**Issue by first-leon** [deimosfr/mediawiki_DeleteHistory#1]
If I choose "Clear History", then removed only version of the existing pages. But the "deleted pages" are not deleted.

It is logical that the deleted page is history.
And logically removed from the base "deleted pages".

**Comment by deimosfr** [comment]
Hi,

Sorry for the late answer, didn't saw the notification. Can you please be more explicit, there is no "Clear History" given by the module.

Thanks
