### ISSUE TITLE
Doesn't work on MediaWiki 1.27.0

### ISSUE THREAD

**Issue by ghost** [deimosfr/mediawiki_DeleteHistory#2]
Doesn't work on 1.27.0
Hello, 
I have updated my wiki to 1.27.0 and the extension doesn't work.

The following message appears when I click DeleteHistory at Special Page:

`Fatal error: Call to undefined function wfMsg() in /var/www/admin/www/wikijournal.ru/extensions/DeleteHistory/DeleteHistory_body.php on line 64`

Thanks

**Comment by deimosfr** [comment]
Hi,

Thanks for reporting the issue. I do not have migrated my MediaWiki yet so didn't encounter the issue. Could you please test if this PR works for you please https://github.com/deimosfr/mediawiki_DeleteHistory/pull/3

**Comment by ghost** [comment]
I can report that this PR works perfectly on MediaWiki 1.27.0.

But there are some errors:

`PHP Strict Standards:  Only variables should be assigned by reference in /extensions/DeleteHistory/DeleteHistory_body.php on line 58`

`PHP Notice:  Undefined variable: out_opt in /extensions/DeleteHistory/DeleteHistory_body.php on line 204`

`PHP Strict Standards:  Only variables should be assigned by reference in /extensions/DeleteHistory/DeleteHistory_body.php on line 20`

**Comment by deimosfr** [comment]
Great thanks

**Comment by ghost** [comment]
Did you see the errors I reported? 
(edited post...)

**Comment by deimosfr** [comment]
No because I didn't used Mediawiki 1.27 yet.
